### ISSUE TITLE
Comparaison notes de cours et diapo - Principes IRM

### ISSUE THREAD

**Issue by me-pic** [methodes-cogneuro/methodes-cogneuro.github.io#116]
Révision du chapitre [Principes IRM](https://methodes-cogneuro.github.io/irm.html) en fonction des diapos du cours

[**Section Spin magnétique et champ B0**](https://methodes-cogneuro.github.io/irm.html#spin-magnetique-et-champ-b0)

- Ajouter dans les notes de cours une phrase sur la relation entre la force de l'aimant et sa taille (diapo 7)
- Ajouter dans les notes de cours une phrase sur la direction aléatoire des spins en l'absence de champ magnétique (diapo 10)

[**Section Résonance magnétique**](https://methodes-cogneuro.github.io/irm.html#resonance-magnetique)

- Ajouter dans les notes de cours une image des antennes (diapo 12)

[**Section Contrastes T1 et T2**](https://methodes-cogneuro.github.io/irm.html#contrastes-t-1-et-t-2)

- Modifier l'axe y pour la [figure 15](https://methodes-cogneuro.github.io/_images/t1.png): Mxy -> Mz
- Ajouter hyperlien pour M0 dans le paragraphe sur la relaxation en T1  vers l'encadré décrivant M0
- Modifier l'axe y pour la figure 18: Mz -> Mxz

**Comment by pbellec** [comment]
fixed by PR #120
